<!DOCTYPE html>
<html>
@php
    $page = 'ok';
@endphp
<head>
    <title>Token Generated</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f5f5f5;
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            align-items: center;
            min-height: 100vh;
        }

        .banner {
            background-color: #007bff;
            color: #fff;
            padding: 10px;
            text-align: center;
            width: 100%;
        }

        .container {
            max-width: 100%; /* Use full width on mobile */
            padding: 20px;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            border-radius: 5px;
            text-align: center;
            margin-top: 20px;
        }

        .token-box {
            border: 2px solid #007bff;
            padding: 20px;
            border-radius: 5px;
        }

        h1 {
            font-size: 24px;
            margin-bottom: 20px;
            color: #333;
        }

        p {
            font-size: 16px;
            color: #333;
            margin-bottom: 10px;
        }

        strong {
            font-size: 20px;
            color: #007bff; /* Blue color */
        }

        /* Media Query for larger screens */
        @media (min-width: 768px) {
            .container {
                max-width: 400px;
            }
        }
    </style>
</head>
<body>
    <div class="banner">
        <p>This is the banner view</p>
    </div>

    <div class="container">
        <h1>Token Generated by Admin</h1>
        <div class="token-box">
            
            <p><strong>{{ $token }}</strong></p>
        </div>
    </div>
</body>
</html>
